### ISSUE TITLE
Using Cocoapods

### ISSUE THREAD

**Issue by arshadsk5** [dmrschmidt/QRCode#2]
I am using pods in my project, how i can install using pods or manually ? please help.

**Comment by dmrschmidt** [comment]
Cocoapods is not currently supported and likely won't be. I'll add support for Swift Package Manager, hopefully soon.

Adding manually however is straightforward. Simply checkout the repo and build the `QRCode` framework target. You can then include the generated framework in your project like any other framework.

**Comment by dmrschmidt** [comment]
well I changed my mind as I was bored right now ;)

`pod 'SimpleQRCode', '~> 0.6.0'`

https://cocoapods.org/pods/SimpleQRCode
