### ISSUE TITLE
Background color is misbehaving in layers on 16.1.1

### ISSUE THREAD

**Issue by nickdnk** [dmrschmidt/QRCode#5]
Hey

This is super weird, but I cannot get the background color to work properly on 16.1.1. It works on 16.1.

If I set the background color to say, red, it will render as pink. It's as if there is a semi-transparent white layer between the background color and the QR code itself. This only seems to affect the rendered image when the image is being used in a CILayer, not when used in a regular UIImageView, which makes it even weirder. It's likely an iOS issue given that it occurred after the above version bump.

Is this something worth looking into for this project, or do we think Apple should fix it?

I tried replacing `try? qrCode.image().cgImage` with just `UImage.init(named: "file").cgImage`, which looks perfectly normal, so it only affects the QRCode image, for some reason.

Code for generating the QRCode looks like this:

```swift
DispatchQueue.global(qos: .userInteractive).async() { [weak self] in
            
            guard let self = self else {return}
            
            var qrCode = QRCode(string: qrCode)!
            qrCode.color = .white
            qrCode.backgroundColor = NyxColors.secondaryBackgroundColor // This is color hex 1A202B
            qrCode.inputCorrection = .low
            qrCode.size = CGSize.init(width: 456, height: 456)
            
            DispatchQueue.main.async() {
                
                UIView.animate(withDuration: 0.3) {
                    self.qrFeedbackContainer.opacity = 0
                    self.qrCodeLayer.contents = try? qrCode.image().cgImage
                    self.qrCodeLayer.opacity = 1
                }
                
            }
        }
```

Don't mind the missing anti-aliasing, it's disabled on the Simulator.

iOS 16.1 - this is how it should look
![Simulator Screen Shot - iPhone 14 Pro - 2022-11-29 at 15 31 16](https://user-images.githubusercontent.com/8411314/204556856-5ef41fb9-b8ca-49cd-aee6-08febea213a0.png)

iOS 16.1.1 - as you can see here, the background is no longer hex 1A202B, but something way brighter.
![IMG_5842](https://user-images.githubusercontent.com/8411314/204557167-57f5feea-c413-48f3-a9e3-ba0a7485646f.PNG)

**Comment by dmrschmidt** [comment]
Hey @nickdnk,

that certainly sounds strange. If I'm understanding you correctly, you do have a working workaround for you though, correct? I'll try to have a look at this later today. Thanks for sharing the code excerpt. I'll get back to you if I need some additional information.

**Comment by nickdnk** [comment]
I don't have a working solution on 16.1.1, no. Simply updating the phone from 16.1 to 1.6.1.1 with the app already installed changes the behavior from normal to that weird semi-white-transparent result.

**Comment by nickdnk** [comment]
The really weird thing is that it works another place in the app where I use the QRCode on a regular view and not a CI layer. Exactly identical color properties for the QRCode and background view there. This is one the weirdest problems I have ever encountered in Swift.

**Comment by dmrschmidt** [comment]
So I've just tried to replicate this issue in the commit above (01efc19), which sits in a new branch [ios1611-layer-drawing](https://github.com/dmrschmidt/QRCode/tree/ios1611-layer-drawing).

I can not reproduce the behavior you're describing there so far. If I transferred your example correct, then `qrCodeLayer` is the `UILayer` of a plain `UIView`. That's how I have it now. The background color is set to plain `UIColor.red` and that's also how it shows (bottom right view).

Could you have a look and see what the difference may be? My phone is running iOS 16.1.1 and I've tried in a 16.0 simulator as well.

![IMG_6702 2](https://user-images.githubusercontent.com/69365/204743071-ffb168d1-7da9-4f2e-83e1-9462cf0ea3ec.PNG)

**Comment by nickdnk** [comment]
Alright. Thanks for the effort.

I suspect this may be related to the QR code being used in a SceneKit scene as a material layer. That's the only difference I see at this point from my cases where it works + your test.

As you can see from the screenshots above, multiple images are being used in the layer, namely the "Chateau Motel" logo top left and the "NYX" logo (red-white square) bottom left. I tried replacing these with a QR code image and the result is identical no matter where on the layer the QR code is being used. I tried messing around with background color properties of the layer the QR code is being applied to, and I've not managed to get it to work yet.

Honestly I have no idea where to go from here, but I'll see if I can produce a small code example where it doesn't work.

**Comment by dmrschmidt** [comment]
Sounds kinda mysterious, yeah. What I often do in these cases is create a new Xcode project with the minimum amount of code to replicate the weird behavior I'm seeing. If that doesn't help to fix the issue, it at least also serves as a great starting point for a stackoverflow question or filing a radar with Apple as a bug. Especially because of the fact that its limited to iOS 16.1.1, it does kinda sound like an Apple bug to me.

If you can isolate the problem that way I can also have a look. Haven't done anything with SceneKit so far however.

**Comment by nickdnk** [comment]
> Sounds kinda mysterious, yeah. What I often do in these cases is create a new Xcode project with the minimum amount of code to replicate the weird behavior I'm seeing. If that doesn't help to fix the issue, it at least also serves as a great starting point for a stackoverflow question or filing a radar with Apple as a bug. Especially because of the fact that its limited to iOS 16.1.1, it does kinda sound like an Apple bug to me.
> 
> If you can isolate the problem that way I can also have a look. Haven't done anything with SceneKit so far however.

Hey

I never had time to look into this. What I did instead was simply to make the QR code layer's background fully transparent and then add another layer behind it with the background color I wanted. That worked like before. I don't think this problem is related to this library, so I'm closing this. Thanks for your time.
